/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ecarl
 */
public class ViewPrincipal extends javax.swing.JFrame {
    ViewProduto produto = new ViewProduto();
    ViewUsuario usuario = new ViewUsuario();
    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbUsuario = new javax.swing.JButton();
        jbProduto = new javax.swing.JButton();
        jbPDV = new javax.swing.JButton();
        jbSobre = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jmTopMenuSide = new javax.swing.JMenuBar();
        jmTopMenu = new javax.swing.JMenu();
        jmUsuario = new javax.swing.JMenuItem();
        jmProduto = new javax.swing.JMenuItem();
        jmPDV = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(119, 198, 131));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jbUsuario.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbUsuario.setText("USUARIO");
        jbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jbUsuario);

        jbProduto.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbProduto.setText("PRODUTO");
        jbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(jbProduto);

        jbPDV.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbPDV.setText("PDV");
        jPanel2.add(jbPDV);

        jbSobre.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbSobre.setText("SOBRE");
        jPanel2.add(jbSobre);

        jbSair.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jbSair.setText("SAIR");
        jPanel2.add(jbSair);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        jmTopMenuSide.setBackground(new java.awt.Color(255, 255, 255));

        jmTopMenu.setBackground(new java.awt.Color(255, 255, 255));
        jmTopMenu.setText("Arquvios");

        jmUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jmUsuario.setText("Usuario");
        jmTopMenu.add(jmUsuario);

        jmProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jmProduto.setBackground(new java.awt.Color(255, 255, 255));
        jmProduto.setText("Produto");
        jmTopMenu.add(jmProduto);

        jmPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmPDV.setBackground(new java.awt.Color(255, 255, 255));
        jmPDV.setText("PDV");
        jmTopMenu.add(jmPDV);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setToolTipText("");
        jmTopMenu.add(jSeparator1);

        jmSair.setBackground(new java.awt.Color(255, 255, 255));
        jmSair.setText("Sair");
        jmTopMenu.add(jmSair);

        jmTopMenuSide.add(jmTopMenu);

        setJMenuBar(jmTopMenuSide);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbProdutoActionPerformed

    private void jbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuarioActionPerformed
        // TODO add your handling code here:
        menuUsuario();
    }//GEN-LAST:event_jbUsuarioActionPerformed
    
    private void menuUsuario (){
        
        jbUsuario.add(usuario);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbPDV;
    private javax.swing.JButton jbProduto;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSobre;
    private javax.swing.JButton jbUsuario;
    private javax.swing.JMenuItem jmPDV;
    private javax.swing.JMenuItem jmProduto;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenu jmTopMenu;
    private javax.swing.JMenuBar jmTopMenuSide;
    private javax.swing.JMenuItem jmUsuario;
    // End of variables declaration//GEN-END:variables
}
